{{- if and .Values.username .Values.password }}
{{- $toolPrefix := include "tool-config.NAME" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tool-config.secret-name" . }}
  labels:
    app.kubernetes.io/name: {{ include "tool-config.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Values.app }}
    app.kubernetes.io/component: {{ .Values.component }}
    chart: {{ include "tool-config.chart" . }}
    release: {{ .Release.Name }}
    group: {{ .Values.group }}
    grouping: {{ .Values.grouping }}
  annotations:
    description: {{ printf "Secret to hold the username and password for %s so that other components can access it" (include "tool-config.name" .) }}
type: Opaque
stringData:
  {{ $toolPrefix }}_PASSWORD: {{ .Values.username | quote }}
  {{ $toolPrefix }}_USER: {{ .Values.password | quote }}
  {{- range $key, $val := .Values.otherSecrets }}
  {{ printf "%s_%s" $toolPrefix (upper $key) }}: {{ $val | quote }}
  {{- end }}
{{- end }}
