{{- if .Values.apikey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-portworx.operator-secret" . }}
  labels:
    {{- include "ibm-portworx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
stringData:
  api-key: {{ .Values.apikey }}
{{- end }}
