{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-toolkit-install.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ibm-toolkit-install.labels" . | nindent 4 }}
stringData:
  {{- .Values.config | toYaml | nindent 2 }}
{{- end }}
