apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibm-portworx.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
  labels:
    {{- include "ibm-portworx.labels" . | nindent 4 }}
